# Linear Regression

In this notebook, we build a Linear Regression model to predict medical insurance charges based on customer information. The model learns the relationship between the input features and the target variable by fitting the best possible linear equation that minimizes prediction error.

The workflow includes:
- Loading the dataset
- Data preprocessing
- Training the Linear Regression model
- Making predictions
- Evaluating model performance using MAE, MSE, RMSE, and R² Score
- Saving the trained model

In [2]:
import pandas as pd
df=pd.read_csv("../data/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Load the Dataset

The first step in Linear Regression is to load the original dataset. We use the raw dataset so that every  step is applied consistently and independently. This ensures that the notebook is reproducible and does not depend on the output of previous notebooks.

In [3]:
X=df.drop("charges",axis=1)
y=df["charges"]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
y_train.shape

(1070,)

In [5]:
X_train["sex"]=X_train["sex"].map({"female":1,"male":0})
X_train["smoker"]=X_train["smoker"].map({"yes":1,"no":0})
X_test["sex"]=X_test["sex"].map({"female":1,"male":0})
X_test["smoker"]=X_test["smoker"].map({"yes":1,"no":0})
X_train

      age  sex     bmi  children  smoker     region
560    46    1  19.950         2       0  northwest
1285   47    1  24.320         0       0  northeast
1142   52    1  24.860         0       0  southeast
969    39    1  34.320         5       0  southeast
486    54    1  21.470         3       0  northwest
...   ...  ...     ...       ...     ...        ...
1095   18    1  31.350         4       0  northeast
1130   39    1  23.870         5       0  southeast
1294   58    0  25.175         0       0  northeast
860    37    1  47.600         2       1  southwest
1126   55    0  29.900         0       0  southwest

[1070 rows x 6 columns]

In [6]:
X_train=pd.get_dummies(X_train,columns=["region"],drop_first=True,dtype=int)
X_test=pd.get_dummies(X_test,columns=["region"],drop_first=True,dtype=int)
X_train

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
560,46,1,19.950,2,0,1,0,0
1285,47,1,24.320,0,0,0,0,0
1142,52,1,24.860,0,0,0,1,0
969,39,1,34.320,5,0,0,1,0
486,54,1,21.470,3,0,1,0,0
...,...,...,...,...,...,...,...,...
1095,18,1,31.350,4,0,0,0,0
1130,39,1,23.870,5,0,0,1,0
1294,58,0,25.175,0,0,0,0,0
860,37,1,47.600,2,1,0,0,1
1126,55,0,29.900,0,0,0,0,1

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[['age','bmi','children']]=scaler.fit_transform(
    X_train[['age','bmi','children']]
)
X_test[['age','bmi','children']]=scaler.transform(
    X_test[['age','bmi','children']]
)
X_train

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
560,0.472227,1,-1.756525,0.734336,0,1,0,0
1285,0.543313,1,-1.033082,-0.911192,0,0,0,0
1142,0.898745,1,-0.943687,-0.911192,0,0,1,0
969,-0.025379,1,0.622393,3.202629,0,0,1,0
486,1.040918,1,-1.504893,1.557100,0,1,0,0
...,...,...,...,...,...,...,...,...
1095,-1.518194,1,0.130717,2.379865,0,0,0,0
1130,-0.025379,1,-1.107579,3.202629,0,0,1,0
1294,1.325264,0,-0.891539,-0.911192,0,0,0,0
860,-0.167551,1,2.820864,0.734336,1,0,0,1
1126,1.112004,0,-0.109327,-0.911192,0,0,0,1

In [12]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [18]:
model.coef_

array([ 3.61497541e+03,  1.85916916e+01,  2.03622812e+03,  5.16890247e+02,
        2.36511289e+04, -3.70677326e+02, -6.57864297e+02, -8.09799354e+02])

In [13]:
model.intercept_

np.float64(-11949.810741967702)

In [10]:
X_train.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

## Model Training

The Linear Regression model is trained using the training dataset. During training, the algorithm learns the relationship between the input features and the target variable by finding the optimal coefficients and intercept that minimize the prediction error.

After training, the model stores:
- Coefficients for each input feature.
- An intercept (bias) value.

These learned parameters are then used to make predictions on unseen data.

In [14]:
y_pred=model.predict(X_test)
y_pred

array([ 8969.55027444,  7068.74744287, 36858.41091155,  9454.67850053,
       26973.17345656, 10864.11316424,   170.28084136, 16903.45028662,
        1092.43093614, 11218.34318352, 28101.68455267,  9377.73460205,
        5263.0595179 , 38416.04221107, 40255.82339284, 37098.25353123,
       15240.39392306, 35912.88264434,  9112.52398703, 31461.92108909,
        3847.68845883, 10130.12001517,  2370.54189389,  7140.21550828,
       11301.76782638, 12961.65366224, 14509.47251876,  6159.8976107 ,
        9963.85857263,  2177.85718217,  9115.93673494, 13073.68932159,
        4561.82376202,  3408.20756033,  4459.81359745, 13032.06505076,
        1979.99357292,  8813.28303302, 33271.29124448, 32585.51583927,
        3908.76090964,  4326.10774721, 14142.81326533, 11423.45494846,
        8774.13955311, 12097.28051001,  5281.57353499,  3150.5596042 ,
       35494.46461214,  9150.1124786 , 15836.84575621,  2343.57470069,
       12364.78414194,  1482.29488266, 13389.06105161, 12573.57395972,
        4341.83680558, 32165.33688042, 13321.3360032 , 12896.82071102,
       14167.99421483, 10506.17623512, 16360.78543548,  7763.89824584,
       11839.25019431,  4061.19750503, 26652.40230125, 10930.14138671,
        2137.41385988,  6209.01123411, 10729.82391284, 11628.3104129 ,
       10981.04528946,  9166.50818596, 11954.27732874,  6747.85121734,
        7248.5304713 , 10735.16710748,  6580.84819774,  8762.00329355,
        3767.13383454, 36632.4975496 ,  6378.11979721, 30842.09248656,
       34846.52451051, 35278.07387112,  7019.444352  , 12861.38414264,
        9942.30149778, 14473.5260648 , 17693.37304474, 35258.24845137,
       33029.58968269,  6185.91730447, 31999.98962535,  9481.33158273,
       29444.04271523,  3674.48498404, 28308.26432106,  5823.36495229,
        5407.76752001,  1883.4947576 , 11499.675042  , 15075.90690632,
       11699.63163008,  4308.82427855,  9895.1840044 , 31708.40056201,
         -86.87094667, 32819.71429004,  3280.69178415, 10183.88853878,
       14318.76389179, 31642.35684542, 11461.57806791,  3929.23701831,
       13107.89313088, 31810.99450607,  8152.02593593,  3238.08417076,
        8439.56108376, 10594.63871458, 15219.68736374,  5647.8808143 ,
        3781.95285499, 10228.944897  , 10900.12933883, 11122.74845192,
       14438.14112575,  7430.31504776,  5386.22676759,  9231.32739901,
        9343.76283713, 12538.27606344,  8337.66982683, 15333.36900871,
        8411.2145439 , 31797.27496298, 35785.91843418, 31603.71967017,
        6011.96229251, 12607.03584641,  6013.5115031 , 14560.79590559,
        2493.47989441, 32963.45524228,  6265.14380504,  5034.62173797,
       14344.81347407,  6941.1412259 , 38670.01270366,  3087.58741836,
        5885.8752536 , 31686.24200595, 11562.61859836,  8476.04749512,
       14806.72486264,  9814.46186143, 27105.71831469, 33453.83352069,
       14551.8999207 ,  1684.36856768, 13166.96197398,  2222.76894041,
        5449.59393727, 11568.96325488, 39807.96912709, 36500.65163031,
       34001.37945748,  3897.27856532,  7456.14132125,  8661.82084477,
       12450.92458882,  4813.53293089,  2047.65528159, 32112.11251984,
       25111.52085938, 17484.27663755, 26411.46181822, 10159.52421   ,
       37260.32666386,  -441.23918333,  6779.55013103,  7781.45337795,
        4367.95988484,  5105.87170813,  5919.18675042,  4305.71645941,
       15191.08806502, 11132.09935114,  6932.80116584,  2525.64793222,
        1536.05183213, 31944.78284317, 16414.12251517, 12011.53367195,
        1268.05926603, 12531.25953189,  1564.93415917,  8737.33621694,
        1873.03940488, 33916.22971211, 10858.38635063,  2603.43633853,
       25674.40250332, 26343.43022704,  9430.91152033,  1800.73500777,
       13261.42480211,  1120.17810533, 10386.66427709, 10567.29006474,
       16944.25995713, 26846.54662457,  6939.11178393,  5193.04710054,
        5846.00017265, 13229.60536846, 11098.33930228,  8362.28134289,
        5135.53940151, 12308.34064139, 13861.17886997, 35773.70926219,
        4157.01930317, 28917.86562624,  -914.37342357,  2873.71150671,
       11046.2540774 , 15683.06950225,  5210.67532324,  6888.38518351,
        3854.31140958, 31312.64705453,  7241.43226665, 12405.99508651,
        5619.17039188,  9528.22557021, 36314.009043  ,  4429.40596906,
        9667.91523953, 31161.15738995,  5747.13292318,  4603.37294255,
        1048.35533791,  4832.6604097 ,  4574.9041044 ,  6507.30666036,
       18659.12407756, -1545.57184934,  2376.4352498 , 10694.62157146,
        3151.28919904, 10209.96361187,  3733.89128353,  5125.08103172,
       12400.90700504,  6218.65296628,  8231.63765089,  7590.50155269,
        8924.15352268, 10482.90359975, 27808.04576398, 39061.50093248,
       11761.4991981 ,  7687.56363151, 40920.29151165, 12318.58665305])

## Evaluation Metrics

Evaluation Metrics is very important procedure where we see our models result.
We get to know how our model is managing the errors and variation and show prediction is accurate or correct it just like result check after the examination

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score
mae=mean_absolute_error(y_test,y_pred)
print("The mean abosulte error is:",mae);
mse=mean_squared_error(y_test,y_pred)
print("The mean squared error is:",mse);
rmse=root_mean_squared_error(y_test,y_pred)
print("The root mean squared error is:",rmse);
r2=r2_score(y_test,y_pred)
print("The r2 score is:",r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
adjusted_r2=1-((1-r2)*(n-1))/(n-p-1)
print("the adjusted_r3 is:",adjusted_r2)