## Ridge Regression

In this notebook, we build a Ridge Regression model to predict medical insurance charges based on customer information. The model learns the relationship between the input features and the target variable by fitting the best possible linear equation that minimizes prediction error.

The workflow includes:
- Loading the dataset
- Data preprocessing
- Training the Linear Regression model
- Making predictions
- Evaluating model performance using MAE, MSE, RMSE, and R² Score
- Saving the trained model

In [1]:
import pandas as pd
df=pd.read_csv("../data/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Load the Dataset

The first step in Linear Regression is to load the original dataset. We use the raw dataset so that every  step is applied consistently and independently. This ensures that the notebook is reproducible and does not depend on the output of previous notebooks.

In [5]:
X=df.drop("charges",axis=1)
y=df["charges"]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
y_train.shape

(1070,)

In [7]:
X_train["sex"]=X_train["sex"].map({"female":1,"male":0})
X_train["smoker"]=X_train["smoker"].map({"yes":1,"no":0})
X_test["sex"]=X_test["sex"].map({"female":1,"male":0})
X_test["smoker"]=X_test["smoker"].map({"yes":1,"no":0})
X_train

      age  sex     bmi  children  smoker     region
560    46    1  19.950         2       0  northwest
1285   47    1  24.320         0       0  northeast
1142   52    1  24.860         0       0  southeast
969    39    1  34.320         5       0  southeast
486    54    1  21.470         3       0  northwest
...   ...  ...     ...       ...     ...        ...
1095   18    1  31.350         4       0  northeast
1130   39    1  23.870         5       0  southeast
1294   58    0  25.175         0       0  northeast
860    37    1  47.600         2       1  southwest
1126   55    0  29.900         0       0  southwest

[1070 rows x 6 columns]

In [8]:
X_train=pd.get_dummies(X_train,columns=["region"],drop_first=True,dtype=int)
X_test=pd.get_dummies(X_test,columns=["region"],drop_first=True,dtype=int)
X_train

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
560,46,1,19.950,2,0,1,0,0
1285,47,1,24.320,0,0,0,0,0
1142,52,1,24.860,0,0,0,1,0
969,39,1,34.320,5,0,0,1,0
486,54,1,21.470,3,0,1,0,0
...,...,...,...,...,...,...,...,...
1095,18,1,31.350,4,0,0,0,0
1130,39,1,23.870,5,0,0,1,0
1294,58,0,25.175,0,0,0,0,0
860,37,1,47.600,2,1,0,0,1
1126,55,0,29.900,0,0,0,0,1

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[['age','bmi','children']]=scaler.fit_transform(
    X_train[['age','bmi','children']]
)
X_test[['age','bmi','children']]=scaler.transform(
    X_test[['age','bmi','children']]
)
X_train

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
560,0.472227,1,-1.756525,0.734336,0,1,0,0
1285,0.543313,1,-1.033082,-0.911192,0,0,0,0
1142,0.898745,1,-0.943687,-0.911192,0,0,1,0
969,-0.025379,1,0.622393,3.202629,0,0,1,0
486,1.040918,1,-1.504893,1.557100,0,1,0,0
...,...,...,...,...,...,...,...,...
1095,-1.518194,1,0.130717,2.379865,0,0,0,0
1130,-0.025379,1,-1.107579,3.202629,0,0,1,0
1294,1.325264,0,-0.891539,-0.911192,0,0,0,0
860,-0.167551,1,2.820864,0.734336,1,0,0,1
1126,1.112004,0,-0.109327,-0.911192,0,0,0,1

In [10]:
from sklearn.linear_model import Ridge
model=Ridge(alpha=0.1)
model.fit(X_train,y_train)

Ridge(alpha=0.1)

In [11]:
y_pred=model.predict(X_test)
y_pred

array([ 8971.35219312,  7071.0448728 , 36845.95923146,  9457.72996213,
       26963.17682952, 10866.97183257,   173.65372961, 16904.99336665,
        1095.21479655, 11221.12714577, 28091.98960536,  9380.70832175,
        5266.76682105, 38405.61528575, 40244.70814066, 37087.89216503,
       15242.68754121, 35901.7738352 ,  9115.58956964, 31450.35334676,
        3852.0605484 , 10133.14964166,  2374.57549339,  7142.17225334,
       11303.73468406, 12962.60512195, 14510.75260876,  6162.72325711,
        9965.50797328,  2182.74760227,  9118.56027736, 13075.01625803,
        4565.55874041,  3411.40804211,  4463.62760179, 13033.85601922,
        1983.38832489,  8815.58391836, 33259.5326525 , 32575.74096407,
        3912.35782656,  4329.78890617, 14144.28402652, 11425.80526892,
        8778.24130984, 12099.82535262,  5284.44097639,  3153.9984279 ,
       35484.46990582,  9154.17182311, 15838.74428586,  2348.55791427,
       12366.42240435,  1485.87834392, 13392.14624557, 12575.63520645,
        4344.94704852, 32154.88430968, 13322.79618438, 12897.78692961,
       14169.30627395, 10509.24850701, 16362.94543384,  7766.29630595,
       11840.37239431,  4064.08343189, 26643.07971451, 10933.9476232 ,
        2140.5900639 ,  6212.48218159, 10732.09750804, 11629.72857191,
       10983.71762457,  9170.52090986, 11957.74942885,  6751.19218055,
        7251.59293193, 10736.83224794,  6584.48994177,  8764.53313713,
        3771.78709901, 36620.48075742,  6380.94436231, 30830.54835186,
       34836.50549844, 35266.3161857 ,  7023.92869985, 12863.55205366,
        9944.38413169, 14475.9988247 , 17693.83983789, 35247.02228742,
       33017.48513174,  6188.99241598, 31990.31465265,  9484.46457509,
       29434.73687644,  3678.35172741, 28297.56627579,  5825.66979389,
        5410.45081762,  1886.7979414 , 11503.11205222, 15078.27736606,
       11701.52356828,  4313.52792428,  9899.06538991, 31698.5399812 ,
         -83.0642627 , 32809.01228539,  3284.59590969, 10187.71213521,
       14319.61651852, 31630.52160455, 11462.88696972,  3933.15971633,
       13109.59027195, 31799.78385145,  8155.39434681,  3241.9145712 ,
        8441.38292497, 10597.4393228 , 15220.56141292,  5652.24438777,
        3784.9948737 , 10230.99782632, 10902.95723257, 11124.90525507,
       14440.26077314,  7434.43059592,  5389.78357368,  9235.46941387,
        9346.97278875, 12539.33757525,  8339.9441472 , 15335.45349946,
        8413.72928678, 31786.63876152, 35773.73004277, 31591.75694984,
        6014.41005609, 12608.05436059,  6017.81199149, 14562.17170833,
        2498.2866632 , 32952.84712835,  6268.60459659,  5037.41022381,
       14346.34190528,  6944.55242312, 38657.71331251,  3090.52315915,
        5890.23818719, 31675.21129514, 11564.38204541,  8478.54747912,
       14808.16926324,  9817.42205339, 27095.90101546, 33442.50707177,
       14552.83575025,  1687.64243613, 13169.44333596,  2226.21938492,
        5453.51648332, 11572.6176079 , 39795.27740162, 36488.2895957 ,
       33989.95297296,  3900.26206082,  7458.60205149,  8664.16542056,
       12452.83144396,  4817.09492661,  2050.91850454, 32102.34409263,
       25101.96307285, 17486.73497574, 26400.90616403, 10161.26570288,
       37247.4153225 ,  -438.08202975,  6782.74387326,  7783.95087113,
        4371.42105085,  5108.51480055,  5922.19451018,  4308.61417218,
       15193.28340153, 11134.51326269,  6936.51271729,  2528.2832697 ,
        1538.80580114, 31934.41928965, 16416.74416088, 12014.04280619,
        1271.39235682, 12532.50495306,  1567.70616361,  8739.4927862 ,
        1876.1313139 , 33905.06270717, 10862.20821956,  2607.49553305,
       25664.89964856, 26333.67707938,  9433.5951156 ,  1804.20844982,
       13264.57244127,  1123.6730268 , 10389.3194887 , 10570.08780236,
       16944.92189229, 26837.52714271,  6943.43583152,  5195.23655308,
        5849.60240509, 13232.24604009, 11100.92851932,  8365.51454807,
        5138.19488162, 12310.64812228, 13864.65119024, 35763.55846401,
        4160.60814818, 28908.54041549,  -910.67222722,  2877.49951759,
       11049.81659677, 15685.53288277,  5215.11769974,  6890.62523057,
        3857.51160877, 31302.07425809,  7243.61655474, 12409.25887935,
        5622.761829  ,  9531.11362014, 36302.98721923,  4433.95394952,
        9669.30203596, 31150.91638363,  5749.67925654,  4607.19069793,
        1052.40301601,  4836.13099684,  4578.00733124,  6510.79618108,
       18661.26385715, -1541.15517044,  2379.662774  , 10697.70387023,
        3154.36220767, 10211.28990695,  3736.8735958 ,  5128.83010721,
       12403.28675131,  6222.04275588,  8234.08936315,  7592.69352098,
        8926.5139697 , 10484.57694598, 27798.8839674 , 39050.53897133,
       11763.00726497,  7690.27000541, 40908.31525037, 12320.34460092])

In [26]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mae=mean_absolute_error(y_test,y_pred)
print("The mean abosulte error is:",mae);
mse=mean_squared_error(y_test,y_pred)
print("The mean squared error is:",mse);
rmse=root_mean_squared_error(y_test,y_pred)
print("The root mean squared error is:",rmse);
r2=r2_score(y_test,y_pred)
print("The r2 score is:",r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
adjusted_r2=1-((1-r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",adjusted_r2)

The mean abosulte error is: 4182.386166709884
The mean squared error is: 33601518.318503276
The root mean squared error is: 5796.681664409672
The r2 score is: 78.3563330948802 %
the adjusted_r2 is: 0.7768780284298461

In [22]:
y_train_pred=model.predict(X_train)
from sklearn.metrics import r2_score

r2_train = r2_score(y_train, y_train_pred)
print("Training R² Score:", r2_train)
r2_test = r2_score(y_test, y_pred)
print("Testing R² Score:", r2_test)

Training R² Score: 0.7417253725960109
Testing R² Score: 0.783563330948802

In [23]:
print(f"Training R² : {r2_train:.4f}")
print(f"Testing R²  : {r2_test:.4f}")

Training R² : 0.7417
Testing R²  : 0.7836

## Training vs Testing Performance
The Training R² Score measures how well the Ridge Regression model fits the training data.
The Testing R² Score measures how well the model generalizes to unseen data.
If the difference between Training R² and Testing R² is small, the model generalizes well and has a lower risk of overfitting.

In [30]:
ridge_coef = model.coef_
print(ridge_coef)
import pandas as pd

coef_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Ridge Coefficient": model.coef_
})

print(coef_df)

[ 3.61438329e+03  1.77893460e+01  2.03593846e+03  5.16958152e+02
  2.36374080e+04 -3.70216573e+02 -6.56364805e+02 -8.09102123e+02]
            Feature  Ridge Coefficient
0               age        3614.383287
1               sex          17.789346
2               bmi        2035.938458
3          children         516.958152
4            smoker       23637.407996
5  region_northwest        -370.216573
6  region_southeast        -656.364805
7  region_southwest        -809.102123

## Observation

- Ridge Regression reduces the magnitude of feature coefficients using L2 regularization.
- None of the coefficients become exactly zero.
- All features remain in the model.
- Smaller coefficients make the model less sensitive to noise, helping reduce overfitting.