## Lasso Regression

In this notebook, we build a Lasso(L1) Regression model to predict medical insurance charges based on customer information. The model learns the relationship between the input features and the target variable by fitting the best possible linear equation that minimizes prediction error.

The workflow includes:
- Loading the dataset
- Data preprocessing
- Training the LassoCv Regression model
- Making predictions
- Evaluating model performance using MAE, MSE, RMSE, and R² Score
- Saving the trained model

In [1]:
import pandas as pd
df=pd.read_csv("../data/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## X and y value sepration

In [22]:
X=df.drop("charges",axis=1)
y=df["charges"]

## Train and test split of X and y

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

## Binary encoding of sex and smoker using pd.map in X_train and X_test

In [24]:
X_train["sex"]=X_train["sex"].map({"female":0,"male":1})
X_test["sex"]=X_test["sex"].map({"female":0,"male":1})
X_train["smoker"]=X_train["smoker"].map({"yes":1,"no":0})
X_test["smoker"]=X_test["smoker"].map({"yes":1,"no":0})

## One Hot Encoding on X_train and X_test for region section section

In [25]:
X_train=pd.get_dummies(X_train,columns=["region"],drop_first=True,dtype=int)
X_test=pd.get_dummies(X_test,columns=["region"],drop_first=True,dtype=int)

## Scaling of the children ,bmi and age columns

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[["age","bmi","children"]]=scaler.fit_transform(
    X_train[["age","bmi","children"]])
X_test[["age","bmi","children"]]=scaler.transform(
    X_test[["age","bmi","children"]])

       age  sex     bmi      children  smoker     region
764   45.0  NaN  25.175  2.000000e+00     NaN  northeast
887   36.0  NaN  30.020 -6.640586e-18     NaN  northwest
890   64.0  NaN  26.885 -6.640586e-18     NaN  northwest
1293  46.0  NaN  25.745  3.000000e+00     NaN  northwest
259   19.0  NaN  31.920 -6.640586e-18     NaN  northwest
...    ...  ...     ...           ...     ...        ...
109   63.0  NaN  35.090 -6.640586e-18     NaN  southeast
575   58.0  NaN  27.170 -6.640586e-18     NaN  northwest
535   38.0  NaN  28.025  1.000000e+00     NaN  northeast
543   54.0  NaN  47.410 -6.640586e-18     NaN  southeast
846   51.0  NaN  34.200  1.000000e+00     NaN  southwest

[268 rows x 6 columns]

In [34]:
from sklearn.linear_model import LassoCV
alpha_=[0.001, 0.01, 0.1, 1, 2, 5, 10, 20, 50, 100, 200, 500, 1000]
lasso_cv_model=LassoCV(
    alphas=alpha_,
    cv=5,
    max_iter=10000,
    random_state=42
)
lasso_cv_model.fit(X_train,y_train)
print("best alpha:",lasso_cv_model.alpha_)

best alpha: 100.0

In [36]:
y_pred=lasso_cv_model.predict(X_test)
y_pred

array([ 8628.41043175,  7171.20026025, 36366.20380711,  9432.64402776,
       26476.05704499, 11205.78438   ,   379.15495786, 16904.07548234,
         987.02637982, 11157.66553559, 27939.53480663,  9362.89068471,
        5601.58537277, 37868.36477286, 39900.76973114, 36653.85029034,
       15339.16957332, 35540.52875517,  9455.48973609, 30987.54584034,
        4180.56487803, 10528.06403309,  2940.48622426,  6763.94780577,
       11228.63562835, 12645.54207723, 14968.40443412,  6078.35043024,
        9603.55476417,  2599.90231399,  9413.62687013, 13136.18707113,
        4904.75594744,  3452.19472648,  4966.38839237, 12654.85891223,
        2516.34621415,  9288.05648728, 32760.71254543, 32258.62111452,
        4170.53430513,  4380.41061135, 14534.23385111, 11580.85955   ,
        8990.03149749, 12606.47538549,  5227.86049893,  3584.59814977,
       35027.53186362,  9335.34519905, 16126.58725332,  2712.72920103,
       12261.78663049,  1295.68607624, 13726.25808518, 12161.7804189 ,
        4153.18902446, 31440.77226441, 13806.479445  , 12574.57198447,
       14664.82559209, 10615.69255312, 16638.2185759 ,  7798.31189652,
       11546.96009342,  4158.18349808, 26419.63292922, 11182.17097752,
        2278.86492601,  6664.87284873, 10330.00049978, 11198.99296521,
       11319.92600922,  9419.10041328, 12194.84420282,  7138.71666778,
        6788.11692575, 10874.19866616,  6816.09985528,  9161.8998413 ,
        4148.38205353, 35792.23184172,  6801.13117557, 29769.43506493,
       34318.49750827, 34385.12129737,  7226.7881717 , 12932.52805992,
        9906.00323725, 14751.62397949, 17179.44226649, 35100.96788033,
       32128.12736601,  5844.98318796, 31668.90116357,  9885.87652351,
       29197.39358715,  4041.18619837, 27697.53204272,  5511.67530202,
        5472.78137183,  2453.23233718, 11778.15297859, 15357.58572667,
       11506.78384557,  4606.52264213, 10163.75398672, 31604.66852936,
        -216.42515332, 32610.79420938,  3817.543221  , 10335.92622795,
       13940.42066714, 30680.90614175, 11110.67152011,  4404.13674744,
       12855.34674383, 31653.35229241,  8406.59994952,  3340.44184157,
        8071.11770647, 10535.54837295, 14710.75480657,  5994.72322245,
        3842.22696449, 10165.23541877, 11152.61469516, 10802.07739163,
       14744.76145675,  7703.85399715,  5792.62282292,  9400.71981391,
        9538.0165889 , 12161.10830666,  8842.6238405 , 15724.90026279,
        8100.08825736, 31743.28317599, 35162.81784191, 30716.02234804,
        6152.83963626, 12278.33473472,  6364.04855527, 14433.02009094,
        2963.51023415, 32832.7921943 ,  6295.51750195,  5591.71836028,
       14169.53111599,  7433.94548334, 37877.90153508,  3224.36659529,
        6173.09748588, 30724.12243333, 11471.79877517,  8171.05835012,
       14509.39815891, 10140.39972656, 26862.6117954 , 32495.40027646,
       14118.21473912,  1791.32554377, 13632.87052683,  2051.70890706,
        5800.96677771, 11759.68599845, 39623.17776309, 35961.99139635,
       33057.01536312,  4444.76205086,  8031.22695378,  9108.12361216,
       12043.8818786 ,  4926.56320762,  2636.90738223, 31895.86967984,
       25105.24944268, 17740.52798849, 25933.55103675, 10327.98050195,
       36387.81195289,  -597.20612427,  6957.00766433,  8217.29387259,
        4029.27230354,  5177.76087178,  5617.82716901,  4880.82149583,
       15321.53272581, 11266.11976612,  7230.24484647,  2283.18728739,
        1363.55055733, 31698.25833155, 16692.29557301, 12338.42938079,
        1390.15317674, 12137.06666145,  1357.40490194,  9321.19745084,
        2079.46270824, 33446.9820332 , 10973.01207031,  2648.02669841,
       25444.96766634, 26195.99602353,  9584.31454986,  1835.21394759,
       13535.3070158 ,  1721.77131512, 11030.40540518, 10950.79979079,
       16321.65549801, 26690.24043978,  7281.18621795,  4955.53375851,
        6197.30823153, 13439.57233879, 11534.88870986,  8639.08676404,
        5180.86648345, 12306.15410384, 13879.2195944 , 35343.48839721,
        4264.33536507, 28703.23555167,  -242.90583798,  3002.20504996,
       11379.29771626, 15672.01920256,  5547.93107838,  7124.81278907,
        4343.6046575 , 31284.77071146,  7473.51759746, 12719.47503407,
        5613.57037557, 10033.29025218, 35837.73281346,  4803.5630001 ,
        9522.53015623, 30926.13645208,  5804.20039581,  4940.40151839,
        1243.21851761,  4949.38810312,  5029.50226934,  6990.40169852,
       18518.48314368, -1256.3939231 ,  2936.74405433, 10999.69186936,
        3751.38009917, 10019.38637347,  3766.32796605,  5434.64593464,
       12954.42170087,  6238.12103764,  8062.95205324,  7133.71612248,
        8852.52640698, 10673.57969867, 27625.27409229, 38775.35599957,
       11880.20241142,  7398.3562792 , 40472.19546348, 12733.86352233])

In [38]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mae=mean_absolute_error(y_test,y_pred)
print("The mean abosulte error is:",mae);
mse=mean_squared_error(y_test,y_pred)
print("The mean squared error is:",mse);
r2=r2_score(y_test,y_pred)
print("The r2 score is:",r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
adjusted_r2=1-((1-r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",adjusted_r2)

The mean abosulte error is: 4268.40263712877
The mean squared error is: 34245283.94567648
The r2 score is: 77.94166585670872 %
the adjusted_r2 is: 0.7726032735035223

In [40]:
y_train_pred=lasso_cv_model.predict(X_train)
from sklearn.metrics import r2_score

r2_train = r2_score(y_train, y_train_pred)
print("Training R² Score:", r2_train)
r2_test = r2_score(y_test, y_pred)
print("Testing R² Score:", r2_test)

Training R² Score: 0.7406181234209634
Testing R² Score: 0.7794166585670872

In [41]:
print(f"Training R² : {r2_train:.4f}")
print(f"Testing R²  : {r2_test:.4f}")

Training R² : 0.7406
Testing R²  : 0.7794

In [43]:
lasso_coef = lasso_cv_model.coef_
print(lasso_coef)
import pandas as pd

coef_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Lasso Coefficient": lasso_cv_model.coef_
})

print(coef_df)

[  256.12656985     0.           324.83592472   362.95054907
 23041.82021516     0.            -0.            -0.        ]
            Feature  Lasso Coefficient
0               age         256.126570
1               sex           0.000000
2               bmi         324.835925
3          children         362.950549
4            smoker       23041.820215
5  region_northwest           0.000000
6  region_southeast          -0.000000
7  region_southwest          -0.000000

In [44]:
coef_df[coef_df["Lasso Coefficient"] == 0]

            Feature  Lasso Coefficient
1               sex                0.0
5  region_northwest                0.0
6  region_southeast               -0.0
7  region_southwest               -0.0

In [45]:
coef_df[coef_df["Lasso Coefficient"] != 0]

    Feature  Lasso Coefficient
0       age         256.126570
2       bmi         324.835925
3  children         362.950549
4    smoker       23041.820215