# Model Comparison

This notebook compares Linear Regression, Ridge Regression, and Lasso Regression based on their predictive performance and coefficient behavior.

The models will be compared using MAE, MSE, RMSE, Training R², Testing R², and coefficient analysis.

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
df=pd.read_csv("../data/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
X=df.drop("charges",axis=1)
y=df["charges"]

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [8]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

      age     sex     bmi  children smoker     region
560    46  female  19.950         2     no  northwest
1285   47  female  24.320         0     no  northeast
1142   52  female  24.860         0     no  southeast
969    39  female  34.320         5     no  southeast
486    54  female  21.470         3     no  northwest
...   ...     ...     ...       ...    ...        ...
1095   18  female  31.350         4     no  northeast
1130   39  female  23.870         5     no  southeast
1294   58    male  25.175         0     no  northeast
860    37  female  47.600         2    yes  southwest
1126   55    male  29.900         0     no  southwest

[1070 rows x 6 columns]

In [9]:
X_train["sex"]=X_train["sex"].map({"female":0,"male":1})
X_test["sex"]=X_test["sex"].map({"female":0,"male":1})
X_train["smoker"]=X_train["smoker"].map({"yes":1,"no":0})
X_test["smoker"]=X_test["smoker"].map({"yes":1,"no":0})

In [10]:
X_train=pd.get_dummies(X_train,columns=["region"],drop_first=True,dtype=int)
X_test=pd.get_dummies(X_test,columns=["region"],drop_first=True,dtype=int)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[["age","bmi","children"]]=scaler.fit_transform(
    X_train[["age","bmi","children"]])
X_test[["age","bmi","children"]]=scaler.transform(
    X_test[["age","bmi","children"]])

In [12]:
linear_regression_model=LinearRegression()
linear_regression_model.fit(X_train,y_train)

LinearRegression()

In [13]:
linear_regression_y_pred=linear_regression_model.predict(X_test)
linear_regression_y_pred

array([ 8969.55027444,  7068.74744287, 36858.41091155,  9454.67850053,
       26973.17345656, 10864.11316424,   170.28084136, 16903.45028662,
        1092.43093614, 11218.34318352, 28101.68455267,  9377.73460205,
        5263.0595179 , 38416.04221107, 40255.82339284, 37098.25353123,
       15240.39392306, 35912.88264434,  9112.52398703, 31461.92108909,
        3847.68845883, 10130.12001517,  2370.54189389,  7140.21550828,
       11301.76782638, 12961.65366224, 14509.47251876,  6159.8976107 ,
        9963.85857263,  2177.85718217,  9115.93673493, 13073.68932159,
        4561.82376202,  3408.20756033,  4459.81359745, 13032.06505076,
        1979.99357292,  8813.28303302, 33271.29124448, 32585.51583927,
        3908.76090964,  4326.10774721, 14142.81326533, 11423.45494846,
        8774.13955311, 12097.28051001,  5281.57353499,  3150.5596042 ,
       35494.46461214,  9150.1124786 , 15836.84575621,  2343.57470069,
       12364.78414194,  1482.29488266, 13389.06105161, 12573.57395972,
        4341.83680558, 32165.33688042, 13321.3360032 , 12896.82071102,
       14167.99421483, 10506.17623512, 16360.78543548,  7763.89824584,
       11839.25019431,  4061.19750503, 26652.40230125, 10930.14138671,
        2137.41385988,  6209.01123411, 10729.82391284, 11628.3104129 ,
       10981.04528946,  9166.50818596, 11954.27732874,  6747.85121734,
        7248.5304713 , 10735.16710748,  6580.84819774,  8762.00329355,
        3767.13383454, 36632.4975496 ,  6378.11979721, 30842.09248656,
       34846.52451051, 35278.07387112,  7019.444352  , 12861.38414264,
        9942.30149778, 14473.5260648 , 17693.37304474, 35258.24845137,
       33029.58968269,  6185.91730447, 31999.98962535,  9481.33158273,
       29444.04271523,  3674.48498404, 28308.26432106,  5823.36495229,
        5407.76752001,  1883.4947576 , 11499.675042  , 15075.90690632,
       11699.63163008,  4308.82427855,  9895.1840044 , 31708.40056201,
         -86.87094667, 32819.71429004,  3280.69178415, 10183.88853878,
       14318.76389179, 31642.35684542, 11461.57806791,  3929.23701831,
       13107.89313088, 31810.99450607,  8152.02593593,  3238.08417076,
        8439.56108376, 10594.63871458, 15219.68736374,  5647.8808143 ,
        3781.95285499, 10228.944897  , 10900.12933883, 11122.74845192,
       14438.14112575,  7430.31504776,  5386.22676759,  9231.32739901,
        9343.76283713, 12538.27606344,  8337.66982683, 15333.36900871,
        8411.2145439 , 31797.27496298, 35785.91843418, 31603.71967017,
        6011.96229251, 12607.03584641,  6013.5115031 , 14560.79590559,
        2493.47989441, 32963.45524228,  6265.14380504,  5034.62173797,
       14344.81347407,  6941.1412259 , 38670.01270366,  3087.58741836,
        5885.8752536 , 31686.24200595, 11562.61859836,  8476.04749512,
       14806.72486264,  9814.46186143, 27105.71831469, 33453.83352069,
       14551.8999207 ,  1684.36856768, 13166.96197398,  2222.76894041,
        5449.59393727, 11568.96325488, 39807.96912709, 36500.65163031,
       34001.37945748,  3897.27856532,  7456.14132125,  8661.82084477,
       12450.92458882,  4813.53293089,  2047.65528159, 32112.11251984,
       25111.52085938, 17484.27663755, 26411.46181822, 10159.52421   ,
       37260.32666386,  -441.23918333,  6779.55013103,  7781.45337795,
        4367.95988484,  5105.87170813,  5919.18675042,  4305.71645941,
       15191.08806502, 11132.09935114,  6932.80116584,  2525.64793222,
        1536.05183213, 31944.78284317, 16414.12251517, 12011.53367195,
        1268.05926603, 12531.25953189,  1564.93415917,  8737.33621694,
        1873.03940488, 33916.22971211, 10858.38635063,  2603.43633853,
       25674.40250332, 26343.43022704,  9430.91152033,  1800.73500777,
       13261.42480211,  1120.17810533, 10386.66427709, 10567.29006474,
       16944.25995713, 26846.54662457,  6939.11178393,  5193.04710054,
        5846.00017265, 13229.60536846, 11098.33930228,  8362.28134289,
        5135.53940151, 12308.34064139, 13861.17886997, 35773.70926219,
        4157.01930317, 28917.86562624,  -914.37342357,  2873.71150671,
       11046.2540774 , 15683.06950225,  5210.67532324,  6888.38518351,
        3854.31140958, 31312.64705453,  7241.43226665, 12405.99508651,
        5619.17039188,  9528.22557021, 36314.009043  ,  4429.40596906,
        9667.91523953, 31161.15738995,  5747.13292318,  4603.37294255,
        1048.35533791,  4832.6604097 ,  4574.9041044 ,  6507.30666036,
       18659.12407756, -1545.57184934,  2376.4352498 , 10694.62157146,
        3151.28919904, 10209.96361187,  3733.89128353,  5125.08103172,
       12400.90700504,  6218.65296628,  8231.63765089,  7590.50155269,
        8924.15352268, 10482.90359975, 27808.04576398, 39061.50093248,
       11761.4991981 ,  7687.56363151, 40920.29151165, 12318.58665305])

In [53]:
lin_mae=mean_absolute_error(y_test,linear_regression_y_pred)
print("The mean abosulte error is:",lin_mae);
lin_mse=mean_squared_error(y_test,linear_regression_y_pred)
print("The mean squared error is:",lin_mse);
lin_rmse = np.sqrt(lin_mse)
print("Root Mean Squared Error:", lin_rmse)
lin_r2=r2_score(y_test,linear_regression_y_pred)
print("The r2 score is:",lin_r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
lin_adjusted_r2=1-((1-lin_r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",lin_adjusted_r2)

The mean abosulte error is: 4181.194473753652
The mean squared error is: 33596915.851361476
Root Mean Squared Error: 5796.284659276274
The r2 score is: 78.35929767120722 %
the adjusted_r2 is: 0.7769085898923679

In [20]:
linear_regression_y_pred_train=linear_regression_model.predict(X_train)
linear_regression_y_pred_train

array([ 7094.54007011,  8344.72998713,  9153.77419778, ...,
       11441.08519155, 37314.37460682, 11453.12102783], shape=(1070,))

In [47]:
lin_r2_train = r2_score(y_train, linear_regression_y_pred_train)
print("Training R² Score:", lin_r2_train)
lin_r2_test = r2_score(y_test, linear_regression_y_pred)
print("Testing R² Score:", lin_r2_test)

Training R² Score: 0.7417255854683333
Testing R² Score: 0.7835929767120722

In [25]:
from sklearn.linear_model import Ridge
model_ridge=Ridge(alpha=0.1)
model_ridge.fit(X_train,y_train)

Ridge(alpha=0.1)

In [27]:
y_pred_ridge=model_ridge.predict(X_test)
y_pred_ridge

array([ 8971.35219312,  7071.0448728 , 36845.95923146,  9457.72996213,
       26963.17682952, 10866.97183257,   173.65372961, 16904.99336665,
        1095.21479655, 11221.12714577, 28091.98960536,  9380.70832175,
        5266.76682105, 38405.61528575, 40244.70814066, 37087.89216503,
       15242.68754121, 35901.7738352 ,  9115.58956964, 31450.35334676,
        3852.0605484 , 10133.14964166,  2374.57549339,  7142.17225334,
       11303.73468406, 12962.60512195, 14510.75260876,  6162.72325711,
        9965.50797328,  2182.74760227,  9118.56027736, 13075.01625803,
        4565.55874041,  3411.40804211,  4463.62760179, 13033.85601922,
        1983.38832489,  8815.58391836, 33259.5326525 , 32575.74096407,
        3912.35782656,  4329.78890617, 14144.28402652, 11425.80526892,
        8778.24130984, 12099.82535262,  5284.44097639,  3153.9984279 ,
       35484.46990582,  9154.17182311, 15838.74428586,  2348.55791427,
       12366.42240435,  1485.87834392, 13392.14624557, 12575.63520645,
        4344.94704852, 32154.88430968, 13322.79618438, 12897.78692961,
       14169.30627395, 10509.24850701, 16362.94543384,  7766.29630595,
       11840.37239431,  4064.08343189, 26643.07971451, 10933.9476232 ,
        2140.5900639 ,  6212.48218159, 10732.09750804, 11629.72857191,
       10983.71762457,  9170.52090986, 11957.74942885,  6751.19218055,
        7251.59293193, 10736.83224794,  6584.48994177,  8764.53313713,
        3771.78709901, 36620.48075742,  6380.94436231, 30830.54835186,
       34836.50549844, 35266.3161857 ,  7023.92869985, 12863.55205366,
        9944.38413169, 14475.9988247 , 17693.83983789, 35247.02228742,
       33017.48513174,  6188.99241598, 31990.31465265,  9484.46457509,
       29434.73687644,  3678.35172741, 28297.56627579,  5825.66979389,
        5410.45081762,  1886.7979414 , 11503.11205222, 15078.27736606,
       11701.52356828,  4313.52792428,  9899.06538991, 31698.5399812 ,
         -83.0642627 , 32809.01228539,  3284.59590969, 10187.71213521,
       14319.61651852, 31630.52160455, 11462.88696972,  3933.15971633,
       13109.59027195, 31799.78385145,  8155.39434681,  3241.9145712 ,
        8441.38292497, 10597.4393228 , 15220.56141292,  5652.24438777,
        3784.9948737 , 10230.99782632, 10902.95723257, 11124.90525507,
       14440.26077314,  7434.43059592,  5389.78357368,  9235.46941387,
        9346.97278875, 12539.33757525,  8339.9441472 , 15335.45349946,
        8413.72928678, 31786.63876152, 35773.73004277, 31591.75694984,
        6014.41005609, 12608.05436059,  6017.81199149, 14562.17170833,
        2498.2866632 , 32952.84712835,  6268.60459659,  5037.41022381,
       14346.34190528,  6944.55242312, 38657.71331251,  3090.52315915,
        5890.23818719, 31675.21129514, 11564.38204541,  8478.54747912,
       14808.16926324,  9817.42205339, 27095.90101546, 33442.50707177,
       14552.83575025,  1687.64243613, 13169.44333596,  2226.21938492,
        5453.51648332, 11572.6176079 , 39795.27740162, 36488.2895957 ,
       33989.95297296,  3900.26206082,  7458.60205149,  8664.16542056,
       12452.83144396,  4817.09492661,  2050.91850454, 32102.34409263,
       25101.96307285, 17486.73497574, 26400.90616403, 10161.26570288,
       37247.4153225 ,  -438.08202975,  6782.74387326,  7783.95087113,
        4371.42105085,  5108.51480055,  5922.19451018,  4308.61417218,
       15193.28340153, 11134.51326269,  6936.51271729,  2528.2832697 ,
        1538.80580114, 31934.41928965, 16416.74416088, 12014.04280619,
        1271.39235682, 12532.50495306,  1567.70616361,  8739.4927862 ,
        1876.1313139 , 33905.06270717, 10862.20821956,  2607.49553305,
       25664.89964856, 26333.67707938,  9433.5951156 ,  1804.20844982,
       13264.57244127,  1123.6730268 , 10389.3194887 , 10570.08780236,
       16944.92189229, 26837.52714271,  6943.43583152,  5195.23655308,
        5849.60240509, 13232.24604009, 11100.92851932,  8365.51454807,
        5138.19488162, 12310.64812228, 13864.65119024, 35763.55846401,
        4160.60814818, 28908.54041549,  -910.67222722,  2877.49951759,
       11049.81659677, 15685.53288277,  5215.11769974,  6890.62523057,
        3857.51160877, 31302.07425809,  7243.61655474, 12409.25887935,
        5622.761829  ,  9531.11362014, 36302.98721923,  4433.95394952,
        9669.30203596, 31150.91638363,  5749.67925654,  4607.19069793,
        1052.40301601,  4836.13099684,  4578.00733124,  6510.79618108,
       18661.26385715, -1541.15517044,  2379.662774  , 10697.70387023,
        3154.36220767, 10211.28990695,  3736.8735958 ,  5128.83010721,
       12403.28675131,  6222.04275588,  8234.08936315,  7592.69352098,
        8926.5139697 , 10484.57694598, 27798.8839674 , 39050.53897133,
       11763.00726497,  7690.27000541, 40908.31525037, 12320.34460092])

In [54]:
rid_mae=mean_absolute_error(y_test,y_pred_ridge)
print("The mean abosulte error is:",rid_mae);
rid_mse=mean_squared_error(y_test,y_pred_ridge)
print("The mean squared error is:",rid_mse);
rid_rmse = np.sqrt(rid_mse)
print("Root Mean Squared Error:", rid_rmse)
rid_r2=r2_score(y_test,y_pred_ridge)
print("The r2 score is:",rid_r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
rid_adjusted_r2=1-((1-rid_r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",rid_adjusted_r2)

The mean abosulte error is: 4182.3861667098845
The mean squared error is: 33601518.31850328
Root Mean Squared Error: 5796.681664409672
The r2 score is: 78.3563330948802 %
the adjusted_r2 is: 0.7768780284298461

In [55]:
y_train_pred=model_ridge.predict(X_train)
rid_r2_train = r2_score(y_train, y_train_pred)
print("Training R² Score:", rid_r2_train)
rid_r2_test = r2_score(y_test, y_pred_ridge)
print("Testing R² Score:", rid_r2_test)

Training R² Score: 0.7417253725960109
Testing R² Score: 0.783563330948802

In [33]:
lasso_model=Lasso(alpha=100)
lasso_model.fit(X_train,y_train)

Lasso(alpha=100)

In [35]:
y_pred_lasso=lasso_model.predict(X_test)
y_pred_lasso

array([ 8.65326886e+03,  7.21177791e+03,  3.62676034e+04,  9.43396969e+03,
        2.65835825e+04,  1.10906023e+04,  6.12276276e+02,  1.66820876e+04,
        1.23034048e+03,  1.11052577e+04,  2.80414207e+04,  9.34551763e+03,
        5.67837651e+03,  3.76563256e+04,  3.96548589e+04,  3.64880749e+04,
        1.51268618e+04,  3.54135524e+04,  9.44999691e+03,  3.10137802e+04,
        4.30793639e+03,  1.04742998e+04,  3.07748839e+03,  6.76846827e+03,
        1.11772317e+04,  1.25466927e+04,  1.48043879e+04,  6.13587684e+03,
        9.59915323e+03,  2.74601842e+03,  9.39664384e+03,  1.30299267e+04,
        4.97537921e+03,  3.61927442e+03,  5.05601512e+03,  1.25226555e+04,
        2.67957998e+03,  9.27784547e+03,  3.27563902e+04,  3.22144663e+04,
        4.27627931e+03,  4.47735873e+03,  1.43748224e+04,  1.15403003e+04,
        8.95731351e+03,  1.25304084e+04,  5.29231976e+03,  3.72837337e+03,
        3.49110993e+04,  9.28233430e+03,  1.59301090e+04,  2.85759183e+03,
        1.21289789e+04,  1.49074555e+03,  1.35941870e+04,  1.20723777e+04,
        4.28502075e+03,  3.14149343e+04,  1.36787322e+04,  1.24747188e+04,
        1.45232029e+04,  1.05109669e+04,  1.64241477e+04,  7.84332000e+03,
        1.14820029e+04,  4.28547407e+03,  2.65485324e+04,  1.11398450e+04,
        2.46567928e+03,  6.67311130e+03,  1.02623526e+04,  1.11310522e+04,
        1.12488202e+04,  9.39228367e+03,  1.20792172e+04,  7.18051333e+03,
        6.81900791e+03,  1.08491569e+04,  6.84662729e+03,  9.16971858e+03,
        4.24372263e+03,  3.57078366e+04,  6.84688896e+03,  2.97739996e+04,
        3.41457015e+04,  3.43095248e+04,  7.25221859e+03,  1.28265761e+04,
        9.87558309e+03,  1.45790142e+04,  1.69457475e+04,  3.50498480e+04,
        3.21292083e+04,  5.92295521e+03,  3.16358753e+04,  9.84887737e+03,
        2.92534489e+04,  4.14054951e+03,  2.78084996e+04,  5.61682400e+03,
        5.55807329e+03,  2.60851969e+03,  1.16641811e+04,  1.51732375e+04,
        1.14763388e+04,  4.68031683e+03,  1.01273284e+04,  3.16444157e+04,
        3.53793630e+01,  3.26157650e+04,  3.92163204e+03,  1.02240501e+04,
        1.38106276e+04,  3.06886240e+04,  1.10540661e+04,  4.49286019e+03,
        1.27706270e+04,  3.16605621e+04,  8.41044503e+03,  3.48008405e+03,
        8.07357040e+03,  1.04741690e+04,  1.45330310e+04,  6.03544471e+03,
        3.98435502e+03,  1.01177528e+04,  1.10724323e+04,  1.07570526e+04,
        1.45854704e+04,  7.67676973e+03,  5.87026578e+03,  9.36290480e+03,
        9.49206866e+03,  1.20474339e+04,  8.83147939e+03,  1.55318081e+04,
        8.09480604e+03,  3.17374898e+04,  3.50360338e+04,  3.07304433e+04,
        6.23163334e+03,  1.21822641e+04,  6.39824467e+03,  1.42657188e+04,
        3.12165130e+03,  3.28177440e+04,  6.36391662e+03,  5.67323351e+03,
        1.40114312e+04,  7.46397651e+03,  3.76911746e+04,  3.36538419e+03,
        6.18512219e+03,  3.07228842e+04,  1.13613026e+04,  8.16677999e+03,
        1.43699411e+04,  1.01128714e+04,  2.69556310e+04,  3.24570285e+04,
        1.39847301e+04,  1.97443287e+03,  1.35396024e+04,  2.23673286e+03,
        5.85423395e+03,  1.16560355e+04,  3.93986856e+04,  3.58528898e+04,
        3.30122364e+04,  4.54731613e+03,  8.09018394e+03,  9.08999633e+03,
        1.19126037e+04,  5.03602023e+03,  2.79630342e+03,  3.19056666e+04,
        2.52642172e+04,  1.74871505e+04,  2.61150693e+04,  1.03271038e+04,
        3.62847335e+04, -3.17129987e+02,  7.04894261e+03,  8.21426101e+03,
        4.17102884e+03,  5.24914053e+03,  5.69400880e+03,  4.98534734e+03,
        1.50995719e+04,  1.12227032e+04,  7.22987546e+03,  2.44118877e+03,
        1.57073189e+03,  3.16597771e+04,  1.64709208e+04,  1.22401036e+04,
        1.58831531e+03,  1.20632600e+04,  1.55014825e+03,  9.33243226e+03,
        2.27444661e+03,  3.34139255e+04,  1.08548772e+04,  2.80196516e+03,
        2.55978346e+04,  2.63433686e+04,  9.58567535e+03,  2.03363689e+03,
        1.33810645e+04,  1.92949173e+03,  1.10215046e+04,  1.09295311e+04,
        1.60614764e+04,  2.68153983e+04,  7.33826620e+03,  5.05725587e+03,
        6.26641228e+03,  1.33382029e+04,  1.14997218e+04,  8.62389242e+03,
        5.24112814e+03,  1.21833694e+04,  1.36806741e+04,  3.52122183e+04,
        4.36265886e+03,  2.87601860e+04,  1.35595741e+01,  3.13689109e+03,
        1.13199459e+04,  1.54531817e+04,  5.59441789e+03,  7.22213854e+03,
        4.47058465e+03,  3.12998511e+04,  7.56142465e+03,  1.25995154e+04,
        5.68189087e+03,  9.98846509e+03,  3.56842481e+04,  4.88165089e+03,
        9.56288109e+03,  3.09092963e+04,  5.85573880e+03,  5.03100346e+03,
        1.44391410e+03,  5.03667222e+03,  5.12707541e+03,  7.02607615e+03,
        1.82068083e+04, -9.61895313e+02,  3.07755380e+03,  1.09202080e+04,
        3.89095621e+03,  1.00300903e+04,  3.87531932e+03,  5.50303319e+03,
        1.28659839e+04,  6.28002342e+03,  8.11773792e+03,  7.16630641e+03,
        8.85361924e+03,  1.06744023e+04,  2.77190101e+04,  3.85826801e+04,
        1.18247426e+04,  7.44072433e+03,  4.01828378e+04,  1.26236788e+04])

In [56]:
lasso_mae=mean_absolute_error(y_test,y_pred_lasso)
print("The mean abosulte error is:",lasso_mae);
lasso_mse=mean_squared_error(y_test,y_pred_lasso)
print("The mean squared error is:",lasso_mse);
lasso_rmse = np.sqrt(lasso_mse)
print("Root Mean Squared Error:", lasso_rmse)
lasso_r2=r2_score(y_test,y_pred_lasso)
print("The r2 score is:",lasso_r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
lasso_adjusted_r2=1-((1-lasso_r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",lasso_adjusted_r2)

The mean abosulte error is: 4248.494464943583
The mean squared error is: 34266072.94587828
Root Mean Squared Error: 5853.722998731515
The r2 score is: 77.92827508694072 %
the adjusted_r2 is: 0.7724652296607402

In [57]:
y_train_pred=lasso_model.predict(X_train)
lasso_r2_train = r2_score(y_train, y_train_pred)
print("Training R² Score:", lasso_r2_train)
lasso_r2_test = r2_score(y_test, y_pred_lasso)
print("Testing R² Score:", lasso_r2_test)

Training R² Score: 0.7404650969661244
Testing R² Score: 0.7792827508694071

In [58]:
comparision=pd.DataFrame({
    "Models":["LinearRegression","RidgeRegression","LassoRegression"],
    "MAE":[lin_mae,rid_mae,lasso_mae],
    "MSE":[lin_mse,rid_mse,lasso_mse],
    "RMSE":[lin_rmse,rid_rmse,lasso_rmse],
    "Train R²": [lin_r2_train, rid_r2_train, lasso_r2_train],
    "Test R²": [lin_r2_test, rid_r2_test, lasso_r2_test]
})
comparision

,Models,MAE,MSE,RMSE,Train R²,Test R²
0,LinearRegression,4181.194474,3.359692e+07,5796.284659,0.741726,0.783593
1,RidgeRegression,4182.386167,3.360152e+07,5796.681664,0.741725,0.783563
2,LassoRegression,4248.494465,3.426607e+07,5853.722999,0.740465,0.779283

## Model Comparison Conclusion

Based on the evaluation metrics, Linear Regression performs slightly better than Ridge and Lasso Regression on this dataset.

Linear Regression achieved the lowest MAE, MSE, and RMSE and the highest Test R² among the three models.

Ridge Regression produced almost identical results to Linear Regression, indicating that the selected regularization strength had very little effect on model performance.

Lasso Regression performed slightly worse in terms of prediction error and Test R². However, Lasso provided feature selection by reducing some coefficients exactly to zero, resulting in a simpler model.

Therefore, for this dataset, Linear Regression provides the best predictive performance, while Lasso provides the advantage of automatic feature selection.